import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { Card, Button, Badge, Modal, Input } from '../../components/ui'
import { LoadingCard } from '../../components/ui/Spinner'
import api from '../../services/api'
import { 
  FileQuestion, 
  Search, 
  Plus,
  Edit2,
  Trash2,
  Eye,
  Check,
  X,
  Brain
} from 'lucide-react'

const AdminQuestions = () => {
  const queryClient = useQueryClient()
  const [search, setSearch] = useState('')
  const [categoryFilter, setCategoryFilter] = useState('')
  const [selectedQuestion, setSelectedQuestion] = useState(null)
  const [showAddModal, setShowAddModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  
  const [formData, setFormData] = useState({
    text: '',
    category: 'dsa',
    difficulty: 'medium',
    expectedAnswer: '',
    hints: '',
    tags: '',
  })

  // Fetch questions
  const { data, isLoading } = useQuery({
    queryKey: ['admin', 'questions', search, categoryFilter],
    queryFn: async () => {
      const params = new URLSearchParams()
      if (search) params.append('search', search)
      if (categoryFilter) params.append('category', categoryFilter)
      params.append('includeUnapproved', 'true') // Include all questions for admin
      
      const response = await api.get(`/admin/questions?${params.toString()}`)
      return response.data?.data || response.data
    },
  })

  // Create question mutation
  const createQuestionMutation = useMutation({
    mutationFn: async (data) => {
      const response = await api.post('/questions', {
        ...data,
        hints: data.hints.split('\n').filter(h => h.trim()),
        tags: data.tags.split(',').map(t => t.trim()).filter(Boolean),
      })
      return response.data
    },
    onSuccess: () => {
      toast.success('Question created')
      queryClient.invalidateQueries(['admin', 'questions'])
      setShowAddModal(false)
      resetForm()
    },
    onError: (error) => {
      toast.error(error.response?.data?.message || 'Failed to create question')
    },
  })

  // Update question mutation
  const updateQuestionMutation = useMutation({
    mutationFn: async ({ id, data }) => {
      const response = await api.put(`/questions/${id}`, {
        ...data,
        hints: data.hints.split('\n').filter(h => h.trim()),
        tags: data.tags.split(',').map(t => t.trim()).filter(Boolean),
      })
      return response.data
    },
    onSuccess: () => {
      toast.success('Question updated')
      queryClient.invalidateQueries(['admin', 'questions'])
      setShowAddModal(false)
      setSelectedQuestion(null)
      resetForm()
    },
    onError: (error) => {
      toast.error(error.response?.data?.message || 'Failed to update question')
    },
  })

  // Delete question mutation
  const deleteQuestionMutation = useMutation({
    mutationFn: async (id) => {
      const response = await api.delete(`/questions/${id}`)
      return response.data
    },
    onSuccess: () => {
      toast.success('Question deleted')
      queryClient.invalidateQueries(['admin', 'questions'])
      setShowDeleteModal(false)
      setSelectedQuestion(null)
    },
    onError: (error) => {
      toast.error(error.response?.data?.message || 'Failed to delete question')
    },
  })

  // Generate AI question mutation
  const generateQuestionMutation = useMutation({
    mutationFn: async (params) => {
      const response = await api.post('/ai/generate-question', params)
      return response.data
    },
    onSuccess: (data) => {
      setFormData({
        text: data.question.text,
        category: data.question.category,
        difficulty: data.question.difficulty,
        expectedAnswer: data.question.expectedAnswer || '',
        hints: (data.question.hints || []).join('\n'),
        tags: (data.question.tags || []).join(', '),
      })
      toast.success('Question generated by AI')
    },
    onError: (error) => {
      toast.error(error.response?.data?.message || 'Failed to generate question')
    },
  })

  const resetForm = () => {
    setFormData({
      text: '',
      category: 'dsa',
      difficulty: 'medium',
      expectedAnswer: '',
      hints: '',
      tags: '',
    })
  }

  const handleEdit = (question) => {
    setSelectedQuestion(question)
    setFormData({
      text: question.text,
      category: question.category,
      difficulty: question.difficulty,
      expectedAnswer: question.expectedAnswer || '',
      hints: (question.hints || []).join('\n'),
      tags: (question.tags || []).join(', '),
    })
    setShowAddModal(true)
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    if (selectedQuestion) {
      updateQuestionMutation.mutate({ id: selectedQuestion._id, data: formData })
    } else {
      createQuestionMutation.mutate(formData)
    }
  }

  const categories = [
    { id: '', name: 'All Categories' },
    { id: 'dsa', name: 'Data Structures & Algorithms' },
    { id: 'web', name: 'Web Development' },
    { id: 'behavioral', name: 'Behavioral/HR' },
    { id: 'system-design', name: 'System Design' },
    { id: 'database', name: 'Database' },
    { id: 'ml', name: 'Machine Learning' },
    { id: 'devops', name: 'DevOps' },
    { id: 'mobile', name: 'Mobile Development' },
  ]

  const getDifficultyColor = (difficulty) => {
    const colors = { easy: 'success', medium: 'warning', hard: 'danger' }
    return colors[difficulty] || 'default'
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Manage Questions</h1>
          <p className="text-gray-600">Create, edit, and manage interview questions</p>
        </div>
        <Button icon={Plus} onClick={() => { resetForm(); setShowAddModal(true); }}>
          Add Question
        </Button>
      </div>

      {/* Filters */}
      <Card>
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              placeholder="Search questions..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
            />
          </div>
          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            className="px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white"
          >
            {categories.map((cat) => (
              <option key={cat.id} value={cat.id}>{cat.name}</option>
            ))}
          </select>
        </div>
      </Card>

      {/* Questions List */}
      <div className="space-y-4">
        {isLoading ? (
          <Card>
            <LoadingCard message="Loading questions..." />
          </Card>
        ) : data?.questions?.length > 0 ? (
          data.questions.map((question) => (
            <Card key={question._id} hover>
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-2 mb-2">
                    <Badge variant={getDifficultyColor(question.difficulty)} size="sm">
                      {question.difficulty}
                    </Badge>
                    <Badge variant="primary" size="sm">
                      {question.category}
                    </Badge>
                    {question.isAIGenerated && (
                      <Badge variant="purple" size="sm">AI Generated</Badge>
                    )}
                    {question.isApproved ? (
                      <Badge variant="success" size="sm">
                        <Check className="w-3 h-3 mr-1" />
                        Approved
                      </Badge>
                    ) : (
                      <Badge variant="warning" size="sm">
                        Pending
                      </Badge>
                    )}
                  </div>
                  <h3 className="font-medium text-gray-900 mb-2">
                    {question.text}
                  </h3>
                  {question.tags && question.tags.length > 0 && (
                    <div className="flex flex-wrap gap-1">
                      {question.tags.map((tag, index) => (
                        <span key={index} className="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded">
                          {tag}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
                <div className="flex items-center space-x-2 ml-4">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleEdit(question)}
                    icon={Edit2}
                  />
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => {
                      setSelectedQuestion(question)
                      setShowDeleteModal(true)
                    }}
                    icon={Trash2}
                    className="text-red-600 hover:bg-red-50"
                  />
                </div>
              </div>
            </Card>
          ))
        ) : (
          <Card className="text-center py-12">
            <FileQuestion className="w-12 h-12 text-gray-300 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-gray-900 mb-2">No Questions Found</h3>
            <p className="text-gray-500 mb-4">Start by adding some questions</p>
            <Button icon={Plus} onClick={() => setShowAddModal(true)}>
              Add Question
            </Button>
          </Card>
        )}
      </div>

      {/* Add/Edit Modal */}
      <Modal
        isOpen={showAddModal}
        onClose={() => {
          setShowAddModal(false)
          setSelectedQuestion(null)
          resetForm()
        }}
        title={selectedQuestion ? 'Edit Question' : 'Add New Question'}
        size="lg"
      >
        <form onSubmit={handleSubmit} className="space-y-4">
          {/* AI Generate Button */}
          {!selectedQuestion && (
            <Button
              type="button"
              variant="outline"
              icon={Brain}
              onClick={() => generateQuestionMutation.mutate({
                category: formData.category,
                difficulty: formData.difficulty,
              })}
              isLoading={generateQuestionMutation.isPending}
              className="w-full"
            >
              Generate with AI
            </Button>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Question Text</label>
            <textarea
              value={formData.text}
              onChange={(e) => setFormData(prev => ({ ...prev, text: e.target.value }))}
              rows={3}
              required
              className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              placeholder="Enter the question..."
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
              <select
                value={formData.category}
                onChange={(e) => setFormData(prev => ({ ...prev, category: e.target.value }))}
                className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white"
              >
                {categories.slice(1).map((cat) => (
                  <option key={cat.id} value={cat.id}>{cat.name}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Difficulty</label>
              <select
                value={formData.difficulty}
                onChange={(e) => setFormData(prev => ({ ...prev, difficulty: e.target.value }))}
                className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white"
              >
                <option value="easy">Easy</option>
                <option value="medium">Medium</option>
                <option value="hard">Hard</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Expected Answer</label>
            <textarea
              value={formData.expectedAnswer}
              onChange={(e) => setFormData(prev => ({ ...prev, expectedAnswer: e.target.value }))}
              rows={3}
              className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              placeholder="Enter the expected answer..."
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Hints (one per line)</label>
            <textarea
              value={formData.hints}
              onChange={(e) => setFormData(prev => ({ ...prev, hints: e.target.value }))}
              rows={2}
              className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              placeholder="Enter hints, one per line..."
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Tags (comma separated)</label>
            <input
              type="text"
              value={formData.tags}
              onChange={(e) => setFormData(prev => ({ ...prev, tags: e.target.value }))}
              className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              placeholder="e.g., arrays, sorting, recursion"
            />
          </div>

          <Modal.Footer>
            <Button type="button" variant="secondary" onClick={() => {
              setShowAddModal(false)
              setSelectedQuestion(null)
              resetForm()
            }}>
              Cancel
            </Button>
            <Button 
              type="submit"
              isLoading={createQuestionMutation.isPending || updateQuestionMutation.isPending}
            >
              {selectedQuestion ? 'Update Question' : 'Create Question'}
            </Button>
          </Modal.Footer>
        </form>
      </Modal>

      {/* Delete Modal */}
      <Modal
        isOpen={showDeleteModal}
        onClose={() => {
          setShowDeleteModal(false)
          setSelectedQuestion(null)
        }}
        title="Delete Question"
      >
        <p className="text-gray-600">
          Are you sure you want to delete this question? This action cannot be undone.
        </p>
        <Modal.Footer>
          <Button variant="secondary" onClick={() => setShowDeleteModal(false)}>
            Cancel
          </Button>
          <Button 
            variant="danger" 
            onClick={() => deleteQuestionMutation.mutate(selectedQuestion._id)}
            isLoading={deleteQuestionMutation.isPending}
          >
            Delete Question
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  )
}

export default AdminQuestions
